@ECHO OFF
REM JAVA HOME
REM KICKC HOME
set KICKC_HOME=%~dp0..
echo KICKC_HOME=%KICKC_HOME% 
REM KCLIB HOME
set KICKC_STDLIB=%KICKC_HOME%\lib
set KICKC_STDINCLUDE=%KICKC_HOME%\include
echo KICKC_STDLIB=%KICKC_STDINCLUDE%
echo KICKC_STDINCLUDE=%KICKC_STDINCLUDE%
set KICKC_FRAGMENT_HOME=%KICKC_HOME%\fragment
echo KICKC_FRAGMENT_HOME=%KICKC_FRAGMENT_HOME%
REM KICKASSEMBLER HOME
REM VICE HOME
REM KICKC_JAR
for %%I in ( %KICKC_HOME%\jar\kickc-*.jar ) do set KICKC_JAR=%%I
echo KICKC_JAR=%KICKC_JAR%

echo java -jar %KICKC_JAR% -I %KICKC_STDINCLUDE% -L %KICKC_STDLIB% -F %KICKC_FRAGMENT_HOME% %*
java -jar %KICKC_JAR% -I %KICKC_STDINCLUDE% -L %KICKC_STDLIB% -F %KICKC_FRAGMENT_HOME% %*