@ECHO OFF
REM JAVA HOME
REM KICKC HOME
set KICKC_HOME=%~dp0..
echo KICKC_HOME=%KICKC_HOME% 
REM KCLIB HOME
set KICKCLIB_HOME=%KICKC_HOME%\stdlib
echo KICKCLIB_HOME=%KICKCLIB_HOME%
REM KICKASSEMBLER HOME
REM VICE HOME

echo java -jar %KICKC_HOME%\lib\kickc-0.5-SNAPSHOT.jar -I %KICKCLIB_HOME% %*
java -jar %KICKC_HOME%\lib\kickc-0.5-SNAPSHOT.jar -I %KICKCLIB_HOME% %*